---
output: github_document
---


<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# bookmarkr

<!-- badges: start -->
<!-- badges: end -->

The goal of bookmarkr is provide links of R books.

## Installation

You can install the development version of bookmarkr from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("edgar-treischl/bookmarkr")
```

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

#df <- readxl::read_excel(here::here("books.xlsx"))

```

```{r setup, eval=T, error=TRUE}
#Get links via: 
bookmarkr::show_link("keyword")
```


```{r}
head(bookmarkr::books)
```

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

#df <- readxl::read_excel("books.xlsx")

#df <- bookmarkr::links()

```






